config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file,
  # see http://guides.rubyonrails.org/routing.html
  resources :events, only: :show
  resource :cart, only: :create
  resource :checkout, only: [:show, :create]

  root to: 'events#index', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :venue
  has_many :tickets

  validates_presence_of :name, :start_at, :end_at
  validate :start_at_bigger_than_today, :end_at_bigger_than_start_at

  has_attached_file :logo
  validates_attachment_content_type :logo,
                                    content_type: %r{\Aimage\/.*\Z}

  private

  def start_at_bigger_than_today
    return unless start_at.present?
    errors.add :start_at, "can't be in the past" if start_at < Time.zone.now
  end

  def end_at_bigger_than_start_at
    return unless start_at.present? && end_at.present?
    errors.add :end_at, "must be bigger than start at" if end_at < start_at
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  validates_presence_of :email
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :ticket
  belongs_to :order
  validates_presence_of :ticket, :order, :quantity, :price
  validate :enougth_tickets

  def enougth_tickets
    if ticket && quantity && quantity > ticket.quantity
      errors.add(:quantity, "not enougth tickets")
      false
    else
      true
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  has_many :order_items
  validates_presence_of :name, :status, :quantity, :price
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  enum status:  {active: "active", inactive: "inactive"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    session[:cart] ||= {}
    session[:cart][params[:ticket_id]] = params[:quantity]
    redirect_to root_path
    # redirect_back(fallback_location: root_path)
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  def show
    @client_token = gateway.client_token.generate
    @order = build_order
    @payment_errors = []
  end

  def create
    nonce_from_the_client = params[:payment_method_nonce]

    @order = build_order

    @payment_errors = []

    Order.transaction do
      if @order.save

        @order.order_items.each do |order_item|
          order_item.ticket.lock!
          order_item.ticket.quantity -= order_item.quantity
        TicketConfirmationJob.perform_now(@order)
          if !order_item.ticket.save
            raise ActiveRecord::Rollback
          end
        end

        result = gateway.transaction.sale(
          amount: (total_amount / 100.0),
          payment_method_nonce: nonce_from_the_client,
          options: {
            submit_for_settlement: true
          }
        )

        if !result.success? && !result.transaction
          @payment_errors = result.errors.map { |error| "Error: #{error.code}: #{error.message}" }
          raise ActiveRecord::Rollback
        end
      end
    end

    if @order.persisted?
      # enviar email
      session[:cart] = {}
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def total_amount
  @order.order_items.sum { |order_item| order_item.quantity * order_item.price }/1000
  end

  def build_order
    order = Order.new(email: params[:email],
      postal_code: params[:postal_code],
      first_name: params[:first_name],
      last_name: params[:last_name],
      country: params[:country],
      address: params[:address],
      city: params[:city])
    session[:cart].each do |ticket_id, quantity|
      ticket = Ticket.find_by(id: ticket_id)
      order.order_items.build(ticket_id: ticket.id, price: ticket.price, quantity: quantity.to_i)
    end
    order
  end

  def gateway
    Braintree::Gateway.new(
      environment: :sandbox,
      merchant_id: "kbm2kth5fh96kk8g",
      public_key: "xbdyknywbcjwtrcy",
      private_key: "cafc899694bfe92fdf57086451f14e79")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where('start_at >= ?', Time.zone.now)
                   .order(start_at: :asc)
                   .limit(3)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkouts/show.html.slim
/= session[:cart].inspect

- if @order.errors.any?
  = @order.errors.full_messages.join(', ')
  - @order.order_items.each do |order_item|
    - if order_item.errors.any?
      = order_item.errors.full_messages.join(', ')

- @payment_errors.each do |error|
  = error

link#bootstrap-css href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" /
script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
script src="//code.jquery.com/jquery-1.11.1.min.js"
/! ---- Include the above in your HEAD tag --------
.container.wrapper
  .row.cart-body
    .col-lg-6.col-md-6.col-sm-6.col-xs-12.col-md-push-6.col-sm-push-6
        /! REVIEW ORDER
        .panel.panel-info
          .panel-heading
            | Review Order
            .pull-right
              small
                p Price
          .panel-body
            .form-group
              .col-xs-12
                .col-sm-12.col-xs-12
                  - @order.order_items.each do |order_item|
                    .row
                      .col-sm-6.col-xs-6
                        h4 = order_item.ticket.name
                        Span>  Ticket for
                        = order_item.ticket.event.name
                        .row
                        = order_item.quantity
                        span>  tickets
                        .row
                        = order_item.price/1000
                        span> €/each
                      .col-sm-6.col-xs-6.text-right
                        = order_item.quantity * order_item.price/1000
                        span> €
                    br/
                    hr/
            .form-group
              .col-xs-12
                strong Order Total
                .pull-right
                  span €
                  span = @order.order_items.sum { |order_item| order_item.quantity * order_item.price }/1000
            /! REVIEW ORDER END
    .col-lg-6.col-md-6.col-sm-6.col-xs-12.col-md-pull-6.col-sm-pull-6
      /! BILLING METHOD
      .panel.panel-info
        .panel-heading Address
        .panel-body
        = form_tag("/checkout", method: "post", id: "payment-form") do
          section
            input#nonce name="payment_method_nonce" type="hidden" /
          .form-group
            .col-md-12
              strong Country:
            .col-md-12
              input.form-control name="country"
          .form-group
            .col-md-6.col-xs-12
              strong First Name:
              input.form-control name="first_name"
            .span1
            .col-md-6.col-xs-12
              strong Last Name:
              input.form-control name="last_name"
          .form-group
            .col-md-12
              strong Address:
            .col-md-12
              input.form-control name="address"
          .form-group
            .col-md-12
              strong City:
            .col-md-12
              input.form-control name="city"
          .form-group
            .col-md-12
              strong Zip / Postal Code:
            .col-md-12
              input.form-control name="postal_code"
          .form-group
            .col-md-12
              strong Email Address:
            .col-md-12
              input.form-control name="email"
          .bt-drop-in-wrapper
            #bt-dropin
          button.btn.btn-primary.btn-submit-fix type="submit"
            span Buy Tickets


script src="https://js.braintreegateway.com/web/dropin/1.10.0/js/dropin.min.js"

javascript:
   var form = document.querySelector('#payment-form');
   var client_token = "#{@client_token}";
   braintree.dropin.create({
     authorization: client_token,
     container: '#bt-dropin',
     paypal: {
       flow: 'vault'
     }
   }, function (createErr, instance) {
     form.addEventListener('submit', function (event) {
       event.preventDefault();
       instance.requestPaymentMethod(function (err, payload) {
         if (err) {
           console.log('Error', err);
           return;
         }

         document.querySelector('#nonce').value = payload.nonce;
         form.submit();
       });
     });
   });

app/views/events/index.html.slim
.jumbotron
  .container
    h1.display-3 Welcome to our Events!
    p Please join us at:

.container
  .row
    - @events.each do |event|
      .col-md-4
        h2 = event.name
        p
          time datetime="#{event.start_at}" = l event.start_at

        p = link_to 'View details »', event_path(event), class: 'btn btn-secondary'

app/views/events/show.html.slim
.jumbotron
  .container
    = image_tag @event.logo, class: 'event-logo'
    h1.display-3 = @event.name
    p
      // NOTE should we have a helper that allow us to display the dates in
      // a different way? we could have many scenarios such as:
      //  * one day event
      //  * an event that spans between months
      //  * an event that spans between years
      //  * an event of multiple months (say what!?)
      time datetime="#{@event.start_at}" = l @event.start_at, format: '%d %B, %Y'
      '
      |-
      '
      time datetime="#{@event.end_at}" = l @event.end_at, format: '%d %B, %Y'

.container
  .row
    .col-md-8
      h2 About
      p = @event.description

      h3 Tickets
      - @event.tickets.each do |t|
        .ticket
          = t.name
          span>
          strong
            = t.price/1000
            span> €
      end
    .col-md-4
      h3 Location
      p = @event.venue.address

      h3 Buy Your Tickets here
      = form_tag("/cart", method: "post") do
        = select_tag 'ticket_id', options_for_select(@event.tickets.collect{ |u| [u.name, u.id] })
        br/
        input name="quantity" placeholder="How Many Tickets?"
        br/
        br/
        button.btn type="submit"
          span Add to Cart

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ruby Exercise
    link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" rel="stylesheet" /

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link#bootstrap-css href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" /
    script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
    script src="//code.jquery.com/jquery-1.11.1.min.js"
  body
    nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
      = link_to 'Events', root_path, class: 'navbar-brand'
      = link_to 'Checkout', checkout_path, class: 'navbar-brand'
    main role="main"
      = yield

app/views/ticket_mailler/ticket_confirmation.html.erb
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Simple Transactional Email</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">This is preheader text. Some clients will show this text as a preview.</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Hi there,</p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;"> You just purchase
                         <% @order.order_items.each do |order_item|%>
                          <strong><%= order_item.quantity %> </strong>tickets for <%= order_item.ticket.event.name %>
                          <% end %>
                        </p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Enjoy your Event
                        </p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
              <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                <tr>
                  <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    Made with &hearts; by Alexandre Fontes.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>